### ISSUE TITLE
Package for creating networks graphs

### ISSUE THREAD

**Issue by ytakemon** [yanhann10/opendata_viz#1]
Hi @yanhann10,

I am looking for a user-friendly R package for creating network graphs, and stumbled onto your [blog](https://towardsdatascience.com/the-network-of-r-python-questions-on-stackoverflow-8f7b149bbdbf). I really like the way those networks looked and wondering if you could share which R package (if it was R-based) you used to generate them.

I did take a peek of this repo, but couldn't figure out where the scripts are located.

Thank you!

**Comment by yanhann10** [comment]
it's ggnetwork https://github.com/yanhann10/opendata_viz/blob/master/r_stackoverflow/r_stackoverflow.Rmd

**Comment by ytakemon** [comment]
Thank you, @yanhann10 !
